edition = "2018"

binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2

brace_style = "PreferSameLine"
color = "Always"
combine_control_expr = true
condense_wildcard_suffixes = false
empty_item_single_line = true
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_bodies = false
format_strings = true
imports_layout = "Horizontal"
# indent_style = "Visual"
imports_granularity = "Module"
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 50
tab_spaces = 2
# trailing_comma = "Always"
type_punctuation_density = "Wide"
comment_width = 120
normalize_comments = true
wrap_comments = true
fn_args_layout = "Tall"
max_width = 120
merge_derives = true
normalize_doc_attributes = true
remove_nested_parens = true
use_small_heuristics = "Max"
use_try_shorthand = true
